sudo: required

language: ruby

services: 
  - docker

script: 
  - docker build -t thomascountz/gifinity .
  - docker run thomascountz/gifinity /bin/sh -c "cd /home/app/gifinity; bundle exec rspec;"

after_script:
  - docker images
