sudo: required

language: ruby

services: 
  - docker

install: 
  - docker build -t thomascountz/gifinity .

script:
  - docker run thomascountz/gifinity /bin/sh -c "cd /home/app/gifinity; bundle exec rspec;"
