- name: "Retrieve Source Code"
  git:
    repo: https://github.com/Thomascountz/gifinity.git
    dest: /home/deploy/gifinity/
  tags: 
    - update-source-only
  notify:
  - restart nginx

- name: "Install Runtime Dependencies"
  bundler:
    chdir: /home/deploy/gifinity/
    deployment_mode: yes
  tags: 
    - update-source-only
  notify:
  - restart nginx

- name: "Upload dotenv File"
  copy:
    src: ../../../../.env
    dest: /home/deploy/gifinity/.env
  tags: 
    - update-source-only
  notify:
  - restart nginx
