---
- name: gifinity
  hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo

  roles:
    - role: geerlingguy.ruby

    - role: geerlingguy.passenger
      passenger_server_name: _
      passenger_app_root: /home/deploy/gifinity/public

    - deploy
